force-app/main/default/objects/Related_Object__c/Related_Object__c.object-meta.xml
<CustomObject>
    <description>Объект RelatedObject нужен для привязки определенного стандартного объекта Lead/Contact/Case.</description>
    <label>Related Object</label>
    <nameField>
        <displayFormat>RO-{00000}</displayFormat>
        <label>Related Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Object__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Related Objects</relationshipLabel>
    <relationshipName>Related_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelatedObjectControllerTest.cls
@isTest
public with sharing class RelatedObjectControllerTest {

    private static final String INVALID_RELATED_OBJECT_RESULT = 'Actual related object must not be null.';

    @testSetup
    static void setup() {
        Contact testContact = new Contact(LastName = 'Happy Contact');
        insert testContact;

        Lead testLead = new Lead(LastName = 'Happy Lead', Company = 'Test Company');
        insert testLead;

        Case testCase = new Case();
        insert testCase;  

        Related_Object__c relatedCaseObject = new Related_Object__c(Related_Case__c = testCase.Id);
        insert relatedCaseObject;
    }

    @isTest
    public static void getRelatedObjectIdPositiveTest() {
        Id result = RelatedObjectController.getRelatedObjectId('Case');
        System.assertNotEquals(null, result, INVALID_RELATED_OBJECT_RESULT);
    }
}