force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>Объект Answer содержит ответ пользователя на определенный вопрос. Связан с Question и ссылается на GroupAnswer.</description>
    <label>Answer</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Group_Answer__c.field-meta.xml
<CustomField>
    <fullName>Group_Answer__c</fullName>
    <label>Group Answer</label>
    <referenceTo>Group_Answer__c</referenceTo>
    <relationshipLabel>Anwers</relationshipLabel>
    <relationshipName>Anwers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Anwers</relationshipLabel>
    <relationshipName>Anwers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group_Answer__c/Group_Answer__c.object-meta.xml
<CustomObject>
    <description>Объект GroupAnswer нужен для группировки и “объединения” Answer определенного пользователя на определенный Survey.Так же он содержит имя Survey, ответы на который он группирует.</description>
    <label>Group Answer</label>
    <nameField>
        <displayFormat>GA-{00000}</displayFormat>
        <label>Group Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Answer__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Group Answers</relationshipLabel>
    <relationshipName>Group_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Объект Question олицетворяет вопрос. Содержит ссылку на survey, общую позицию вопроса в списке и флажок видимости (True по дефолту). Видимость вопроса важна, если у нас связанные вопрос, и зависимый вопрос не должен быть виден по достижении условий. Содержит сам текст вопроса, флажок переиспользования вопроса, и его тип(picklist, radiobutton, checkbox и т.д.).</description>
    <label>Question</label>
    <nameField>
        <displayFormat>SQ-{00000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Object__c/Related_Object__c.object-meta.xml
<CustomObject>
    <description>Объект RelatedObject нужен для привязки определенного стандартного объекта Lead/Contact/Case.</description>
    <label>Related Object</label>
    <nameField>
        <displayFormat>RO-{00000}</displayFormat>
        <label>Related Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Object__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Related Objects</relationshipLabel>
    <relationshipName>Related_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SurveyUserControllerTest.cls
@IsTest
public with sharing class SurveyUserControllerTest {
    
    private static final String INVALID_RELATED_OBJECT_ID_RESULT = 'Invalid related object id result.';
    private static final String INVALID_SAVE_ANSWERS_RESULT = 'Invalid answers saving.';
    private static final String INVALID_SAVE_GROUP_ANSWER_RESULT = 'Invalid group answer saving.';
    private static final String INVALID_QUESTIONS_AMOUNT = 'Invalid questions amount.';
    private static final String INVALID_SURVEY_NAME = 'Actual survey name doesn\'t equal to expected.';
    
    private static final String TEST_CASE_SUBJECT = 'Printing Gives Error on Internet Explorer';
    
    @TestSetup
    static void makeData() {
        Survey__c testSurvey = TestDataFactory.createSurvey();
        insert testSurvey;
        
        Case testCaseFirst = new Case(Subject = TEST_CASE_SUBJECT);
        insert testCaseFirst;
        
        Related_Object__c testCaseRelatedObject = new Related_Object__c(Related_Case__c = testCaseFirst.Id);
        insert testCaseRelatedObject;
        
        Group_Answer__c testGroupAnswer = new Group_Answer__c();
        testGroupAnswer.Survey__c = testSurvey.Id;
        insert testGroupAnswer;
        
        List<Question__c> testQuestions = TestDataFactory.createQuestions(5, testSurvey.Id);
        insert testQuestions;
    }
    
    private static Id getTestSurveyId() {
        Survey__c testSurvey = [SELECT Id FROM Survey__c WHERE Name = :TestDataFactory.TEST_VALUE];
        return testSurvey.Id;      
    }
    
    private static Id getTestCaseId() {
        Case testCase = [SELECT Id, Subject FROM Case WHERE Subject =: TEST_CASE_SUBJECT];
        return testCase.Id;                 
    }
    
    private static Id getTestQuestionId() {
        Question__c testQuestion = [SELECT Id FROM Question__c WHERE Survey__c = :getTestSurveyId() LIMIT 1];
        return testQuestion.Id;
    }
    
    private static List<Question__c> getTestQuestions() {
        List<Question__c> testQuestions = [SELECT Id FROM Question__c WHERE Survey__c = :getTestSurveyId()];
        return testQuestions;
    }
    
    private static Id getTestGroupAnswerId() {
        Group_Answer__c testGroupAnswer = [SELECT Id FROM Group_Answer__c WHERE Survey__c =: getTestSurveyId()];
        return testGroupAnswer.Id;
    }
    
    
    @isTest
    static void testRelatedObjectIdByStandardObjectId() {
        Id res = SurveyUserController.getRelatedObjectIdByStandardObjectId(getTestCaseId());
        System.assertNotEquals(null, res, INVALID_RELATED_OBJECT_ID_RESULT);
    }
    
    @isTest
    static void testSaveAnswers() {
        AuraHandledException auraExc = null;
        try {
            Answer__c testAnswer = new Answer__c(Group_Answer__c = getTestGroupAnswerId(), Question__c = getTestQuestionId(), Value__c = 'Test Value');
            List<Answer__c> answers = new List<Answer__c>();
            answers.add(testAnswer);
            SurveyUserController.saveAnswers(answers);
        } catch(AuraHandledException exc) {
            auraExc = exc;
        }
        System.assertEquals(null, auraExc, INVALID_SAVE_ANSWERS_RESULT);
    }
    
    @isTest
    static void testPositiveSaveGroupAnswer() {
        Group_Answer__c testGroupAnswer = new Group_Answer__c(Survey__c = getTestSurveyId());
        Id savedGroupAnswerId = SurveyUserController.saveGroupAnswer(testGroupAnswer);
        System.assertNotEquals(null, savedGroupAnswerId, INVALID_SAVE_GROUP_ANSWER_RESULT);
    }
    
    @isTest
    static void testGetQuestions(){
        Integer expectedSize = getTestQuestions().size();
        Integer actualSize = SurveyUserController.getQuestions(getTestSurveyId()).size();
        System.assertEquals(expectedSize, actualSize, INVALID_QUESTIONS_AMOUNT);
    }
    
    @isTest
    static void testGetSurveyById(){
        Survey__c survey = SurveyUserController.getSurveyById(getTestSurveyId());
        System.assertEquals(TestDataFactory.TEST_VALUE, survey.Name, INVALID_SURVEY_NAME);
    }
}