force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>Объект Answer содержит ответ пользователя на определенный вопрос. Связан с Question и ссылается на GroupAnswer.</description>
    <label>Answer</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Group_Answer__c.field-meta.xml
<CustomField>
    <fullName>Group_Answer__c</fullName>
    <label>Group Answer</label>
    <referenceTo>Group_Answer__c</referenceTo>
    <relationshipLabel>Anwers</relationshipLabel>
    <relationshipName>Anwers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group_Answer__c/Group_Answer__c.object-meta.xml
<CustomObject>
    <description>Объект GroupAnswer нужен для группировки и “объединения” Answer определенного пользователя на определенный Survey.Так же он содержит имя Survey, ответы на который он группирует.</description>
    <label>Group Answer</label>
    <nameField>
        <displayFormat>GA-{00000}</displayFormat>
        <label>Group Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Answer__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Group Answers</relationshipLabel>
    <relationshipName>Group_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SurveyUserController.cls
public without sharing class SurveyUserController {
  @AuraEnabled(cacheable=true)
  public static Id getRelatedObjectIdByStandardObjectId(Id standardObjectId) {
    return RelatedObjectController.getRelatedObjectIdByStandardObjectId(standardObjectId);
  }

  @AuraEnabled(cacheable=true)
  public static List<QuestionWrapper> getQuestions(Id surveyId){
    return AnswerFormController.getQuestions(surveyId);
  }

  @AuraEnabled
  public static Id saveGroupAnswer(Group_Answer__c groupAnswer) {
    return GroupAnswerController.saveGroupAnswer(groupAnswer);
  }
  
  @AuraEnabled
  public static void saveAnswers(List<Answer__c> answers) {
    AnswerController.saveAnswers(answers);
  }

  @AuraEnabled(cacheable=false)
  public static Survey__c getSurveyById(Id surveyId) {
    return SurveyController.getSurveyById(surveyId);
  }
}