force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>Объект Answer содержит ответ пользователя на определенный вопрос. Связан с Question и ссылается на GroupAnswer.</description>
    <label>Answer</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Group_Answer__c.field-meta.xml
<CustomField>
    <fullName>Group_Answer__c</fullName>
    <label>Group Answer</label>
    <referenceTo>Group_Answer__c</referenceTo>
    <relationshipLabel>Anwers</relationshipLabel>
    <relationshipName>Anwers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Anwers</relationshipLabel>
    <relationshipName>Anwers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group_Answer__c/Group_Answer__c.object-meta.xml
<CustomObject>
    <description>Объект GroupAnswer нужен для группировки и “объединения” Answer определенного пользователя на определенный Survey.Так же он содержит имя Survey, ответы на который он группирует.</description>
    <label>Group Answer</label>
    <nameField>
        <displayFormat>GA-{00000}</displayFormat>
        <label>Group Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Answer__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Group Answers</relationshipLabel>
    <relationshipName>Group_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Объект Question олицетворяет вопрос. Содержит ссылку на survey, общую позицию вопроса в списке и флажок видимости (True по дефолту). Видимость вопроса важна, если у нас связанные вопрос, и зависимый вопрос не должен быть виден по достижении условий. Содержит сам текст вопроса, флажок переиспользования вопроса, и его тип(picklist, radiobutton, checkbox и т.д.).</description>
    <label>Question</label>
    <nameField>
        <displayFormat>SQ-{00000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <description>The background color of the survey.</description>
    <label>Background Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnswerControllerTest.cls
@isTest
public with sharing class AnswerControllerTest {

    private static final String INVALID_SAVE_ANSWERS_RESULT = 'Invalid answer/answers saving.';

    @TestSetup
    static void setup() {
        Survey__c testSurvey = new Survey__c(Name = 'Test', Background_Color__c = '#A3FF88');
        insert testSurvey;

        Group_Answer__c testGroupAnswer = new Group_Answer__c(Survey__c = testSurvey.Id);
        insert testGroupAnswer;

        Question__c testQuestion = new Question__c();
    }

    private static Id getTestSurveyId() {
        Survey__c testSurvey = [SELECT Id
                                FROM Survey__c
                                WHERE Name = 'Test'];
        return testSurvey.Id;      
    }

    private static Id getTestGroupAnswerId() {
        Group_Answer__c testGroupAnswer = [SELECT Id
                                           FROM Group_Answer__c
                                           WHERE Survey__c =: getTestSurveyId()];
        return testGroupAnswer.Id;
    }

    @isTest
    static void testPositiveSaveAnswer() {
        Answer__c testAnswer = new Answer__c(Group_Answer__c = getTestGroupAnswerId(), );
        Id savedAnswerId = AnswerController.saveAnswer(testAnswer);
        System.assertNotEquals(null, savedAnswerId, INVALID_SAVE_ANSWERS_RESULT);
    }
}