force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <description>The background color of the survey.</description>
    <label>Background Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/IsStandard__c.field-meta.xml
<CustomField>
    <fullName>IsStandard__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the survey is available for reuse.</description>
    <label>IsStandard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ссылка на следующий опрос в цепочке.</description>
    <label>Related To</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SurveyController.cls
public inherited sharing class SurveyController {
  @AuraEnabled(cacheable=true)
  public static List<Survey__c> getAllSurveys() {
    return [SELECT Id, Name 
            FROM Survey__c
            WITH SECURITY_ENFORCED
            LIMIT 50000];
  }

  @AuraEnabled(cacheable=false)
  public static List<Survey__c> getTemplateSurveys() {
    return [SELECT Id, Name
            FROM Survey__c
            WHERE IsStandard__c = TRUE
            WITH SECURITY_ENFORCED
            LIMIT 50000];
  }

  @AuraEnabled(cacheable=false)
  public static Survey__c getSurveyById(Id surveyId) {
    return [SELECT Id, Name, Background_Color__c, Logo__c, Related_To__c, Description__c
            FROM Survey__c
            WHERE Id = :surveyId
            WITH SECURITY_ENFORCED
            LIMIT 1];
  }
}