force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/IsStandard__c.field-meta.xml
<CustomField>
    <fullName>IsStandard__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the survey is available for reuse.</description>
    <label>IsStandard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SurveyControllerTest.cls
@IsTest
public with sharing class SurveyControllerTest {
    private static final String TEST_NAME = 'Test Name';
    
    private static final Integer AMOUNT = 5;
    
    private static final String INVALID_SURVEYS_AMOUNT = 'Actual length of surveys list doesn\'t equal to expected.';
    private static final String INVALID_SURVEY_NAME = 'Actual survey name doesn\'t equal to expected.';
    
    @IsTest
    static void testGetAllSurveys() {
        List<Survey__c> surveys = new List<Survey__c>();
        for (Integer i = 1; i <= AMOUNT; i++) {
            Survey__c survey = TestDataFactory.createSurvey();
            surveys.add(survey);
        }
        insert surveys;
        
        List<Survey__c> allSurveys = SurveyController.getAllSurveys();
        System.assertEquals(AMOUNT, allSurveys.size(), INVALID_SURVEYS_AMOUNT);
    }
    
    @IsTest
    static void testGetStandardSurvey() {
        List<Survey__c> surveys = new List<Survey__c>();
        for (Integer i = 1; i <= AMOUNT; i++) {
            Survey__c survey = TestDataFactory.createSurvey();
            survey.IsStandard__c = true;
            surveys.add(survey);
        }
        insert surveys;
        
        List<Survey__c> templateSurveys = SurveyController.getTemplateSurveys();
        System.assertEquals(AMOUNT, templateSurveys.size(), INVALID_SURVEYS_AMOUNT);
        
        for (Integer i = 1; i <= AMOUNT; i++) {
            Survey__c survey = templateSurveys[i - 1];
            System.assertEquals(TestDataFactory.TEST_VALUE, survey.Name, INVALID_SURVEY_NAME);
        }
    } 
    
    @IsTest
    static void testGetSurveyById() {
		Survey__c survey = TestDataFactory.createSurvey();
        insert survey;
        Survey__c savedSurvey = SurveyController.getSurveyById(survey.Id);
        System.assertEquals(TestDataFactory.TEST_VALUE, savedSurvey.Name, INVALID_SURVEY_NAME);
    }
}