force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Объект Question олицетворяет вопрос. Содержит ссылку на survey, общую позицию вопроса в списке и флажок видимости (True по дефолту). Видимость вопроса важна, если у нас связанные вопрос, и зависимый вопрос не должен быть виден по достижении условий. Содержит сам текст вопроса, флажок переиспользования вопроса, и его тип(picklist, radiobutton, checkbox и т.д.).</description>
    <label>Question</label>
    <nameField>
        <displayFormat>SQ-{00000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/IsReusable__c.field-meta.xml
<CustomField>
    <fullName>IsReusable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsReusable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>RadioButton</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Rating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
<CustomObject>
    <description>The Question Option object is used to store the Question answer options, if the second type implies a type with a choice of answer options (for example, picklist).</description>
    <label>Question Option</label>
    <nameField>
        <displayFormat>QO-{00000}</displayFormat>
        <label>Question Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Options</relationshipLabel>
    <relationshipName>Question_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QuestionController.cls
public with sharing class QuestionController {
  @AuraEnabled(cacheable=false)
  public static List<QuestionWrapper> getStandardQuestions() {
    List<Question__c> questions = [SELECT Id, Label__c, Type__c, Required__c,
                                          (SELECT Value__c 
                                          FROM Question_Options__r 
                                          LIMIT 223)
                                  FROM Question__c
                                  WHERE IsReusable__c = TRUE
                                  WITH SECURITY_ENFORCED
                                  LIMIT 223];

    List<QuestionWrapper> questionsWrappers = new List<QuestionWrapper>();

    for(Question__c question: questions) {
      QuestionWrapper wrapper = new QuestionWrapper(question, question.Question_Options__r);
      questionsWrappers.add(wrapper);
    }

    return questionsWrappers;
  }

  @AuraEnabled(cacheable=false)
  public static List<QuestionWrapper>  getTemplatesQuestions(List<Id> surveyIds) {
    List<Question__c> questions = [SELECT Id, Label__c, Type__c, Required__c, Survey__c,
                                          (SELECT Value__c 
                                          FROM Question_Options__r 
                                          LIMIT 223)
                                  FROM Question__c
                                  WHERE Survey__c IN :surveyIds
                                  WITH SECURITY_ENFORCED
                                  LIMIT 223];

    List<QuestionWrapper> questionsWrappers = new List<QuestionWrapper>();

    for(Question__c question: questions) {
      QuestionWrapper wrapper = new QuestionWrapper(question, question.Question_Options__r);
      questionsWrappers.add(wrapper);
    }

    return questionsWrappers;
  }
}