force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Объект Question олицетворяет вопрос. Содержит ссылку на survey, общую позицию вопроса в списке и флажок видимости (True по дефолту). Видимость вопроса важна, если у нас связанные вопрос, и зависимый вопрос не должен быть виден по достижении условий. Содержит сам текст вопроса, флажок переиспользования вопроса, и его тип(picklist, radiobutton, checkbox и т.д.).</description>
    <label>Question</label>
    <nameField>
        <displayFormat>SQ-{00000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>The position of the question in the survey.</description>
    <label>Position</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <description>The background color of the survey.</description>
    <label>Background Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ссылка на следующий опрос в цепочке.</description>
    <label>Related To</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AnswerFormControllerTest.cls
@isTest
public with sharing class AnswerFormControllerTest {

    private static final String INVALID_QUESTIONS_AMOUNT = 'Invalid questions amount.';
    private static final String INVALID_CONNECTED_SURVEY_ID = 'Invalid connected survey Id.';

    @TestSetup
    static void setup(){
        Survey__c survey = new Survey__c(Name = 'Test', Background_Color__c = '#A3FF88');
        insert survey;

        Survey__c connectedSurvey = new Survey__c(Name = 'TestConnected', Background_Color__c = '#A3FF88', Related_To__c = survey.Id);
        insert connectedSurvey;

        List<Question__c> questions = new List<Question__c>();

        for(Integer i=0; i < 10; i++){
        Question__c testQuestion = new Question__c(Survey__c = survey.Id, Label__c = 'Test label' + i, Position__c = '2');
        questions.add(testQuestion);
        }

        insert questions; 
    }

    private static Id getTestSurveyId() {
        Survey__c testSurvey = [SELECT Id
                                FROM Survey__c
                                WHERE Name = 'Test'];
        return testSurvey.Id;      
    }

    private static Id getTestConnectedSurveyId() {
        Survey__c testSurvey = [SELECT Id
                                FROM Survey__c
                                WHERE Name = 'TestConnected'];
        return testSurvey.Id;      
    }

    private static List<Question__c> getTestQuestions() {
        List<Question__c> questions = [SELECT Id
                                       FROM Question__c];
        return questions;      
    }

    @isTest
    static void testGetQuestions(){
        Integer expectedSize = getTestQuestions().size();
        Integer actualSize = AnswerFormController.getQuestions(getTestSurveyId()).size();
        System.assertEquals(expectedSize, actualSize, INVALID_QUESTIONS_AMOUNT);
    }

    @isTest
    static void testGetConnectedSurveyId(){
        Id expectedId = getTestConnectedSurveyId();
        Id actualId = AnswerFormController.getConnectedSurveyId(getTestSurveyId());
        System.assertEquals(expectedId, actualId, INVALID_CONNECTED_SURVEY_ID);
    }
}