force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Объект Question олицетворяет вопрос. Содержит ссылку на survey, общую позицию вопроса в списке и флажок видимости (True по дефолту). Видимость вопроса важна, если у нас связанные вопрос, и зависимый вопрос не должен быть виден по достижении условий. Содержит сам текст вопроса, флажок переиспользования вопроса, и его тип(picklist, radiobutton, checkbox и т.д.).</description>
    <label>Question</label>
    <nameField>
        <displayFormat>SQ-{00000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/IsVisible__c.field-meta.xml
<CustomField>
    <fullName>IsVisible__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Используется для зависимых вопросов.</description>
    <label>IsVisible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>The position of the question in the survey.</description>
    <label>Position</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>RadioButton</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Rating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
<CustomObject>
    <description>The Question Option object is used to store the Question answer options, if the second type implies a type with a choice of answer options (for example, picklist).</description>
    <label>Question Option</label>
    <nameField>
        <displayFormat>QO-{00000}</displayFormat>
        <label>Question Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Options</relationshipLabel>
    <relationshipName>Question_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Validation__c/Validation__c.object-meta.xml
<CustomObject>
    <description>Объект Validation необходим для реализации связки вопросов и логики отображения некоторых. Имеет ссылку на вопрос поставщика зависимости SurveyQuestion, ссылку на зависимый вопрос того же типа и условие в виде строки.
Объект Answer содержит ответ пользователя на определенный вопрос. Связан с Survey Question и ссылается на GroupAnswer.</description>
    <label>Validation</label>
    <nameField>
        <label>Validation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Validations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Validation__c/fields/Dependent_Question__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Question__c</fullName>
    <description>Link to dependent question.</description>
    <label>Dependent Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Validations</relationshipLabel>
    <relationshipName>Dependent_Question_Validations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Validation__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Validation__c/fields/Related_Question__c.field-meta.xml
<CustomField>
    <fullName>Related_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Validations (Related Question)</relationshipLabel>
    <relationshipName>Validations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Validation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>IS NULL</fullName>
        <default>true</default>
        <label>IS NULL</label>
    </customValue>
    <customValue>
        <fullName>CONTAINS</fullName>
    </customValue>
    <customValue>
        <fullName>EQUALS</fullName>
    </customValue>
    <customValue>
        <fullName>NOT EQUALS</fullName>
    </customValue>
    <customValue>
        <fullName>GREATER THAN</fullName>
    </customValue>
    <customValue>
        <fullName>LESS THAN</fullName>
    </customValue>
    <customValue>
        <fullName>NOT CONTAINS</fullName>
    </customValue>
    <masterLabel>Operators</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AnswerFormController.cls
public with sharing class AnswerFormController {
    @AuraEnabled(cacheable=true)
    public static List<Question__c> getQuestions(Id surveyId){
        return [SELECT Id, Label__c, IsVisible__c, Position__c, Required__c, Type__c,
        (SELECT Id, Question__c, Value__c FROM Question_Options__r),
        (SELECT Id, Related_Question__c, Dependent_Question__c, Operator__c, Value__c FROM Validations1__r)
        FROM Question__c 
        WHERE Survey__c =: surveyId
        WITH SECURITY_ENFORCED];
    }
}