force-app/main/default/objects/Email_Receiver__c/Email_Receiver__c.object-meta.xml
<CustomObject>
    <description>The Email Receiver object is required to store information about the recipient of emails. It will be used to check whether an invitation to this Survey has already been sent to a specific email.</description>
    <label>Email Receiver</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Email Receiver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Receivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Receiver__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Email Receivers</relationshipLabel>
    <relationshipName>Email_Receivers_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Email_Receiver__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>User Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Receiver__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The name of the group of users who will receive the email or the single email.</description>
    <label>Value</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyEmailConfig__c/SurveyEmailConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Набор настроек для создания и отправки электронного письма.</description>
    <label>SurveyEmailConfig</label>
</CustomObject>

force-app/main/default/objects/SurveyEmailConfig__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyEmailConfig__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendEmailLogic.cls
public with sharing class SendEmailLogic {
    
    private static final String EMAIL_SETTINGS_NAME = 'Main';

    @AuraEnabled(cacheable=true)
    public static void sendEmails(List<Email_Receiver__c> emailReceiverList){
        Map<Id, Survey__c> surveyMap = SendEmailLogicHelper.createSurveyMap();
 
        List<Messaging.SingleEmailMessage> emailsForSend = createEmailMessages(emailReceiverList, surveyMap);
        if(emailsForSend.size() > 0){
            Messaging.sendEmail(emailsForSend);
        }
    }
    
    public static List<Messaging.SingleEmailMessage> createEmailMessages(List<Email_Receiver__c> receiverList, Map<Id, Survey__c> surveyMap){
        Organization currentOrg = SendEmailLogicHelper.getOrganization();
        EmailTemplate template = SendEmailLogicHelper.getEmailTemplate();
        Map<String, List<User>> userMap = SendEmailLogicHelper.initializeUserByGroupMap();
        Map<String, List<Id>> contactMap = SendEmailLogicHelper.initializeContactByCampaignMap();
        Map<String, List<Id>> leadMap = SendEmailLogicHelper.initializeLeadByCampaignMap();
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        SurveyEmailConfig__c config = SurveyEmailConfig__c.getValues(EMAIL_SETTINGS_NAME);
        
        for(Email_Receiver__c receiver: receiverList){
            Survey__c survey = surveyMap.get(receiver.Survey__c);
            String body = SendEmailLogicHelper.createEmailBody(template.Body, survey, currentOrg);
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            switch on receiver.Type__c {
                when 'User Group' {
                    String groupName = receiver.Value__c;
                    List<User> userForSend = userMap.get(groupName);
                    for(User user: userForSend){
                        mail = createSingleEmail(user.Id, body, config);
                        emails.add(mail);
                    }
                }
                when 'Campaign' {
                    String campaignName = receiver.Value__c;
                    List<Id> contactForSend = contactMap.get(campaignName);
                    List<Id> leadForSend = leadMap.get(campaignName);

                    if(contactForSend.size() > 0){
                        for(Id contactId: contactForSend){
                            mail = createSingleEmail(contactId, body, config);
                            emails.add(mail);
                        }
                    }

                    if(leadForSend.size() > 0){
                        for(Id leadId: leadForSend){
                            mail = createSingleEmail(leadId, body, config);
                            emails.add(mail);
                        }
                    }
                }
                when 'Record'{
                    mail = createSingleEmail(receiver.Value__c, body, config);
                    emails.add(mail);
                }
            }
        }
        
        return emails;
    }

    public static Messaging.SingleEmailMessage createSingleEmail(Id idForSent, String mailBody, SurveyEmailConfig__c config){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setTargetObjectId(idForSent);
        mail.setSaveAsActivity(false);
        mail.setSenderDisplayName(config.Display_Name__c);
        mail.setSubject(config.Subject__c);
        mail.setBccSender(false);
        mail.setUseSignature(false);
        mail.setPlainTextBody(mailBody);

        return mail;
    }
}