force-app/main/default/objects/Email_Receiver__c/Email_Receiver__c.object-meta.xml
<CustomObject>
    <description>The Email Receiver object is required to store information about the recipient of emails. It will be used to check whether an invitation to this Survey has already been sent to a specific email.</description>
    <label>Email Receiver</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Email Receiver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Receivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Receiver__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Email Receivers</relationshipLabel>
    <relationshipName>Email_Receivers_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Email_Receiver__c/fields/Survey_URL__c.field-meta.xml
<CustomField>
    <fullName>Survey_URL__c</fullName>
    <description>URL for survey</description>
    <label>Survey URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Email_Receiver__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>User Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Receiver__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The name of the group of users who will receive the email or the single email.</description>
    <label>Value</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Guest_URL__c.field-meta.xml
<CustomField>
    <fullName>Guest_URL__c</fullName>
    <description>URL for Guest Users</description>
    <label>Guest URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Link to this survey.</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/Trigger_Rule__c.object-meta.xml
<CustomObject>
    <description>Определяет для какого объекта и при выполнении каких критериев будет производиться дальнейшее действие.</description>
    <label>Trigger Rule</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Trigger Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trigger Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Rule__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <label>Field Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Api_Name__c</fullName>
    <label>Object Api Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_Api_Names</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Trigger Rules</relationshipLabel>
    <relationshipName>Trigger_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Object_Api_Names.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <masterLabel>Object Api Names</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>IS NULL</fullName>
        <default>true</default>
        <label>IS NULL</label>
    </customValue>
    <customValue>
        <fullName>CONTAINS</fullName>
    </customValue>
    <customValue>
        <fullName>EQUALS</fullName>
    </customValue>
    <customValue>
        <fullName>NOT EQUALS</fullName>
    </customValue>
    <customValue>
        <fullName>GREATER THAN</fullName>
    </customValue>
    <customValue>
        <fullName>LESS THAN</fullName>
    </customValue>
    <customValue>
        <fullName>NOT CONTAINS</fullName>
    </customValue>
    <masterLabel>Operators</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerRulesHandler.cls
public with sharing class TriggerRulesHandler {

    private static final String RECEIVER_RECORD_TYPE = 'Record';
    private static final String CASE_OBJECT_NAME = 'Case';

    private static Map<Id, Survey__c> surveyMap;
    
    public static void checkRuleCriterias(String sObjectName, List<ChangedFieldWrapper> changedFields){
        List<Trigger_Rule__c> triggerRules = getTriggerRules(sObjectName);
        List<Email_Receiver__c> receiverList = new List<Email_Receiver__c>();
        surveyMap = getSurveysMap();

        for(ChangedFieldWrapper recordFields: changedFields){
            for(Trigger_Rule__c rule: triggerRules){
                String ruleFieldName = rule.Field_Name__c.tolowercase();
                
                if(recordFields.fieldname == ruleFieldName){
                    if(compareFieldValues(recordFields, rule.Operator__c, rule.Field_Value__c)){
                        Email_Receiver__c receiver = createReceiver(SObjectName, recordFields, rule.Survey__c);
                        receiverList.add(receiver);
                    }
                }
            }
        }

        if(receiverList.size() > 0 && Email_Receiver__c.SObjectType.getDescribe().isCreateable()){
            insert receiverList;
            SendEmailLogic.sendEmails(receiverList);
        }
    }
    
    public static Email_Receiver__c createReceiver(String sObjectName, ChangedFieldWrapper recordFields, String surveyId){
        Id receiverId = SObjectName == CASE_OBJECT_NAME ? recordFields.ownerId : recordFields.recordId;
        Survey__c survey = surveyMap.get(surveyId);
        String surveyUrl = SObjectName == CASE_OBJECT_NAME ? survey.URL__c : survey.Guest_URL__c;
        Email_Receiver__c receiver = new Email_Receiver__c(Type__c = RECEIVER_RECORD_TYPE,
                                                            Survey__c = surveyId,
                                                            Value__c = receiverId,
                                                            Survey_URL__c = surveyUrl);
        return receiver;
    }
    
    public static Boolean compareFieldValues(ChangedFieldWrapper changedField, String operator, Object ruleFieldValue){
        Boolean isConditionMet = false;
        FieldComparable comparator = defineComparingType(changedField);

        switch on operator {
            when 'IS NULL'{
                isConditionMet = comparator.isNull(changedField.newValue, ruleFieldValue);
            }
            when 'EQUALS'{
                isConditionMet = comparator.isEquals(changedField.newValue, ruleFieldValue);
            }
            when 'NOT EQUALS'{
                isConditionMet = comparator.isNotEquals(changedField.newValue, ruleFieldValue);
            }
            when 'CONTAINS'{
                TextFieldComparable textComparator = (TextFieldComparable)comparator;
                isConditionMet = textComparator.isContains(changedField.newValue, ruleFieldValue);
            }
            when 'NOT CONTAINS'{
                TextFieldComparable textComparator = (TextFieldComparable)comparator;
                isConditionMet = textComparator.isNotContains(changedField.newValue, ruleFieldValue);
            }
            when 'GREATER THAN'{
                DateNumberFieldComparable numberComparator = (DateNumberFieldComparable)comparator;
                isConditionMet = numberComparator.isGreater(changedField.newValue, ruleFieldValue);
            }
            when 'LESS THAN'{
                DateNumberFieldComparable numberComparator = (DateNumberFieldComparable)comparator;
                isConditionMet = numberComparator.isLess(changedField.newValue, ruleFieldValue);
            }
            when 'ANY CHANGE'{
                isConditionMet = true;
            }
        }
        
        return isConditionMet;
    }
    
    public static FieldComparable defineComparingType(ChangedFieldWrapper changedField){        
        FieldComparable comparator;
        Schema.DisplayType fieldType = changedField.fieldType;
        
        switch on fieldType{
            when DATE{
                comparator = new DateFieldComparator();
            }
            when DATETIME{
                comparator = new DateTimeFieldComparator();
            }
            when DOUBLE, INTEGER, CURRENCY, PERCENT{
                comparator = new DecimalFieldComparator();
            }
            when else{
                comparator = new TextFieldComparator();
            }
        }
        
        return comparator;
    }
    
    public static List<Trigger_Rule__c> getTriggerRules(String objectApiName){
        return [SELECT Id, Name, Field_Name__c, Operator__c, Field_Value__c, Survey__c, Object_Api_Name__c
                FROM Trigger_Rule__c 
                WHERE Object_Api_Name__c =: objectApiName
                WITH SECURITY_ENFORCED
                LIMIT 50000];
    }

    private static Map<Id, Survey__c> getSurveysMap() {
      List<Survey__c> surveyList = [SELECt URL__c, Guest_URL__c
                                    FROM Survey__c
                                    WITH SECURITY_ENFORCED
                                    LIMIT 50000];
      Map<Id, Survey__c> surveyMap = new Map<Id, Survey__c>();
      for (Survey__c survey : surveyList) {
        surveyMap.put(survey.Id, survey);
      }
      return surveyMap;
    }
}