force-app/main/default/objects/Email_Receiver__c/Email_Receiver__c.object-meta.xml
<CustomObject>
    <description>The Email Receiver object is required to store information about the recipient of emails. It will be used to check whether an invitation to this Survey has already been sent to a specific email.</description>
    <label>Email Receiver</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Email Receiver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Receivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Receiver__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Email Receivers</relationshipLabel>
    <relationshipName>Email_Receivers_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Email_Receiver__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>User Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Receiver__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The name of the group of users who will receive the email or the single email.</description>
    <label>Value</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Rule__c/Trigger_Rule__c.object-meta.xml
<CustomObject>
    <description>Определяет для какого объекта и при выполнении каких критериев будет производиться дальнейшее действие.</description>
    <label>Trigger Rule</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Trigger Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trigger Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Rule__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <label>Field Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Api_Name__c</fullName>
    <label>Object Api Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_Api_Names</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Trigger Rules</relationshipLabel>
    <relationshipName>Trigger_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Object_Api_Names.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <masterLabel>Object Api Names</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>IS NULL</fullName>
        <default>true</default>
        <label>IS NULL</label>
    </customValue>
    <customValue>
        <fullName>CONTAINS</fullName>
    </customValue>
    <customValue>
        <fullName>EQUALS</fullName>
    </customValue>
    <customValue>
        <fullName>NOT EQUALS</fullName>
    </customValue>
    <customValue>
        <fullName>GREATER THAN</fullName>
    </customValue>
    <customValue>
        <fullName>LESS THAN</fullName>
    </customValue>
    <customValue>
        <fullName>NOT CONTAINS</fullName>
    </customValue>
    <masterLabel>Operators</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    static final List<String> NUMBER_DATE_OPERATORS = new List<String>{'IS NULL', 'EQUALS', 'NOT EQUALS', 'LESS THAN', 'GREATER THAN'};
    static final List<String> OTHER_FIELD_OPERATORS = new List<String>{'IS NULL', 'EQUALS', 'NOT EQUALS', 'CONTAINS', 'NOT CONTAINS'};
            
    public static void createTriggerRules(Id surveyId){
        Survey__c testSurvey = new Survey__c(Name = 'Test Survey');
        insert testSurvey;
                
        Map<String, List<String>> fieldTypeOperators = new Map<String, List<String>>();
                
        fieldTypeOperators.put('DATE', NUMBER_DATE_OPERATORS);
        fieldTypeOperators.put('DATETIME', NUMBER_DATE_OPERATORS);
        fieldTypeOperators.put('DOUBLE', NUMBER_DATE_OPERATORS);
        fieldTypeOperators.put('TEXT', OTHER_FIELD_OPERATORS);
                
        List<Trigger_Rule__c> triggerRules = new List<Trigger_Rule__c>();
                
        for(String fieldType: fieldTypeOperators.keySet()){
            for(String operator: fieldTypeOperators.get(fieldType)){
                Trigger_Rule__c triggerRule;
                switch on fieldType{
                    when 'DATE'{
                        triggerRule = new Trigger_Rule__c(Field_Name__c = 'Birthdate',
                                                                  Operator__c = operator,
                                                                  Field_Value__c = '4/28/2020',
                                                                  Object_Api_Name__c = 'Contact',
                                                                  Survey__c = testSurvey.Id);
                    }
                    when 'DATETIME'{
                        triggerRule = new Trigger_Rule__c(Field_Name__c = 'EmailBouncedDate', 
                                                                  Operator__c = operator,
                                                                  Field_Value__c = '10/14/2019, 11:46 AM', 
                                                                  Object_Api_Name__c = 'Contact', 
                                                                  Survey__c = testSurvey.Id);
                    }
                    when 'DOUBLE'{
                        triggerRule = new Trigger_Rule__c(Field_Name__c = 'MailingLatitude',
                                                                  Operator__c = operator,
                                                                  Field_Value__c = '12345', 
                                                                  Object_Api_Name__c = 'Contact', 
                                                                  Survey__c = testSurvey.Id);
                    }
                    when else{
                        triggerRule = new Trigger_Rule__c(Field_Name__c = 'SuppliedEmail', 
                                                                  Operator__c = operator,
                                                                  Field_Value__c = 'Test Email', 
                                                                  Object_Api_Name__c = 'Case', 
                                                                  Survey__c = testSurvey.Id);
                    }
                }
                triggerRules.add(triggerRule);
            }
        }
                
        insert triggerRules;
    }
    
    public static Id createSurvey(){
        Survey__c testSurvey = new Survey__c(Name = 'Test Survey');
        insert testSurvey;
        return testSurvey.Id;
    }
    
    public static void createEmailReceivers(Id surveyId){
        List<Email_Receiver__c> emailReceivers = new List<Email_Receiver__c>();
        for(Integer i=0; i<5; i++){
            Email_Receiver__c emailReceiver = new Email_Receiver__c(Survey__c = surveyId, Type__c='Email',
                                                                    Value__c='mail' + i);
            emailReceivers.add(emailReceiver);
        }
        
        insert emailReceivers;
    }
    
    public static void createContacts(){
        List<Contact> contactList = new List<Contact>();
        
        Date testBirthdate = Date.parse('4/28/2021'); 
        Datetime testEmailBouncedDate = Datetime.parse('10/14/2018, 11:46 AM');
        
        for(Integer i=0; i<5; i++){
            Contact testContact = new Contact(LastName = 'Test Name',
                                              Birthdate = testBirthdate,
                                              EmailBouncedDate = testEmailBouncedDate,
                                              MailingLongitude = 15,
                                              MailingLatitude = 15);
            contactList.add(testContact);
        }
        
        insert contactList;
    }
    
    public static void createCases(){
        List<Case> caseList = new List<Case>();
        
        for(Integer i=0; i<5; i++){
            Case testCase = new Case(SuppliedEmail = 'Email' + i + '@vjv.com');
            caseList.add(testCase);
        }
        
        insert caseList;
    }
    
    public static void createLeads(){
        List<Lead> leadList = new List<Lead>();
        
        for(Integer i=0; i<5; i++){
            Lead testLead = new Lead(LastName = 'Test Name', Industry='Apparel', Company = 'VJV');
            leadList.add(testLead);
        }
        
        insert leadList;
    }
}