force-app/main/default/objects/Email_Receiver__c/Email_Receiver__c.object-meta.xml
<CustomObject>
    <description>The Email Receiver object is required to store information about the recipient of emails. It will be used to check whether an invitation to this Survey has already been sent to a specific email.</description>
    <label>Email Receiver</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Email Receiver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Receivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Receiver__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Email Receivers</relationshipLabel>
    <relationshipName>Email_Receivers_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Email_Receiver__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>User Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Receiver__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The name of the group of users who will receive the email or the single email.</description>
    <label>Value</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Объект Question олицетворяет вопрос. Содержит ссылку на survey, общую позицию вопроса в списке и флажок видимости (True по дефолту). Видимость вопроса важна, если у нас связанные вопрос, и зависимый вопрос не должен быть виден по достижении условий. Содержит сам текст вопроса, флажок переиспользования вопроса, и его тип(picklist, radiobutton, checkbox и т.д.).</description>
    <label>Question</label>
    <nameField>
        <displayFormat>SQ-{00000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>The position of the question in the survey.</description>
    <label>Position</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>RadioButton</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Rating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
<CustomObject>
    <description>The Question Option object is used to store the Question answer options, if the second type implies a type with a choice of answer options (for example, picklist).</description>
    <label>Question Option</label>
    <nameField>
        <displayFormat>QO-{00000}</displayFormat>
        <label>Question Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Options</relationshipLabel>
    <relationshipName>Question_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Rule__c/Trigger_Rule__c.object-meta.xml
<CustomObject>
    <description>Определяет для какого объекта и при выполнении каких критериев будет производиться дальнейшее действие.</description>
    <label>Trigger Rule</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Trigger Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trigger Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Rule__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <label>Field Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Api_Name__c</fullName>
    <label>Object Api Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_Api_Names</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Rule__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Trigger Rules</relationshipLabel>
    <relationshipName>Trigger_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Validation__c/Validation__c.object-meta.xml
<CustomObject>
    <description>Объект Validation необходим для реализации связки вопросов и логики отображения некоторых. Имеет ссылку на вопрос поставщика зависимости SurveyQuestion, ссылку на зависимый вопрос того же типа и условие в виде строки.
Объект Answer содержит ответ пользователя на определенный вопрос. Связан с Survey Question и ссылается на GroupAnswer.</description>
    <label>Validation</label>
    <nameField>
        <label>Validation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Validations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Validation__c/fields/Dependent_Question__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Question__c</fullName>
    <description>Link to dependent question.</description>
    <label>Dependent Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Validations</relationshipLabel>
    <relationshipName>Dependent_Question_Validations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Validation__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Validation__c/fields/Related_Question__c.field-meta.xml
<CustomField>
    <fullName>Related_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Validations (Related Question)</relationshipLabel>
    <relationshipName>Validations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Validation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Object_Api_Names.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <masterLabel>Object Api Names</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>IS NULL</fullName>
        <default>true</default>
        <label>IS NULL</label>
    </customValue>
    <customValue>
        <fullName>CONTAINS</fullName>
    </customValue>
    <customValue>
        <fullName>EQUALS</fullName>
    </customValue>
    <customValue>
        <fullName>NOT EQUALS</fullName>
    </customValue>
    <customValue>
        <fullName>GREATER THAN</fullName>
    </customValue>
    <customValue>
        <fullName>LESS THAN</fullName>
    </customValue>
    <customValue>
        <fullName>NOT CONTAINS</fullName>
    </customValue>
    <masterLabel>Operators</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SaverControllerTestDataFactory.cls
@IsTest
public with sharing class SaverControllerTestDataFactory {

  private static final String TEST_SURVEY_NAME = 'Test Survey Name';
  private static final String TEST_QUESTION_NAME = 'Test Question Name';
  private static final String TEST_QUESTION_TYPE = 'Picklist';
  private static final String TEST_OPTION_VALUE = 'Test Option value';
  private static final String TEST_FIELD_NAME = 'Test Field Name';
  private static final String TEST_RULE_OPERATOR = 'EQUALS';
  private static final String TEST_FIELD_VALUE = 'Test Field value';
  private static final String TEST_OBJECT_API_NAME = 'Contact';
  private static final String TEST_VALIDATION_OPERATOR = 'CONTAINS';
  private static final String TEST_VALUE = 'Test Value';
  private static final String TEST_RECEIVER_TYPE = 'Email';
  private static final String TEST_RECEIVER_VALUE = 'test@bk.ru';

  public static Survey__c createSurvey() {
    Survey__c survey = new Survey__c();
    survey.Name = TEST_SURVEY_NAME;
    return survey;
  }

  public static List<Trigger_Rule__c> createTriggerRuleList(Integer amount, String surveyId) {
    List<Trigger_Rule__c> rules = new List<Trigger_Rule__c>();
    for(Integer i = 0; i < amount; i++) {
      Trigger_Rule__c rule = SaverControllerTestDataFactory.createTriggerRule(surveyId);
      rules.add(rule);
    }
    return rules;
  }

  public static List<Question__c> createQuestionList(Integer amount, String surveyId) {
    List<Question__c> questions = new List<Question__c>();
    for(Integer i = 0; i < amount; i++) {
      Question__c question = SaverControllerTestDataFactory.createQuestion(surveyId, i+ 1);
      questions.add(question);
    }
    return questions;
  }

  public static List<Question_Option__c> createOptionList(Integer amount, String questionId) {
    List<Question_Option__c> options = new List<Question_Option__c>();
    for(Integer j = 0; j < amount; j++) {
      Question_Option__c option = SaverControllerTestDataFactory.createOption(questionId);
      options.add(option);
    } 
    return options;
  }

  public static List<Email_Receiver__c> createEmailReceiverList(Integer amount, String surveyId) {
    List<Email_Receiver__c> receivers = new List<Email_Receiver__c>();
    for(Integer j = 0; j < amount; j++) {
      Email_Receiver__c receiver = SaverControllerTestDataFactory.createEmailReceiver(surveyId);
      receivers.add(receiver);
    } 
    return receivers;
  }

  private static Question_Option__c createOption(String questionId) {
    Question_Option__c option = new Question_Option__c();
    option.Value__c = TEST_OPTION_VALUE;
    option.Question__c = questionId;
    return option;
  }

  private static Question__c createQuestion(String surveyId, Integer position) {
    Question__c question = new Question__c();
    question.Label__c =  TEST_QUESTION_NAME;
    question.Type__c = TEST_QUESTION_TYPE;
    question.Survey__c = surveyId;
    question.Position__c = position;
    return question;
  }

  public static Validation__c  createValidation(String relatedQuestionId, String dependentQuestionId) {
    Validation__c validation = new validation__c();
    validation.Related_Question__c = relatedQuestionId;
    validation.Dependent_Question__c = dependentQuestionId;
    validation.Operator__c = TEST_VALIDATION_OPERATOR;
    validation.Value__c = TEST_VALUE;
    return validation;
  }

  private static Trigger_Rule__c  createTriggerRule(String surveyId) {
    Trigger_Rule__c rule = new Trigger_Rule__c();
    rule.Field_Name__c = TEST_FIELD_NAME;
    rule.Operator__c = TEST_RULE_OPERATOR;
    rule.Field_Value__c = TEST_FIELD_VALUE;
    rule.Object_Api_Name__c = TEST_OBJECT_API_NAME;
    rule.Survey__c = surveyId;
    return rule;
  }

  private static Email_Receiver__c  createEmailReceiver(String surveyId) {
    Email_Receiver__c receiver = new Email_Receiver__c();
    receiver.Type__c = TEST_RECEIVER_TYPE;
    receiver.Value__c = TEST_RECEIVER_VALUE;
    receiver.Survey__c = surveyId;
    return receiver;
  }
}