force-app/main/default/objects/Group_Answer__c/Group_Answer__c.object-meta.xml
<CustomObject>
    <description>Объект GroupAnswer нужен для группировки и “объединения” Answer определенного пользователя на определенный Survey.Так же он содержит имя Survey, ответы на который он группирует.</description>
    <label>Group Answer</label>
    <nameField>
        <displayFormat>GA-{00000}</displayFormat>
        <label>Group Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Answer__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Group Answers</relationshipLabel>
    <relationshipName>Group_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>The Survey object represents the questionnaire itself. It stores the name, description, logo of the questionnaire, and a link to the next poll in the chain, as well as a link to its form. An additional field is a checkbox responsible for whether the survey is standard.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GroupAnswerControllerTest.cls
@isTest
public with sharing class GroupAnswerControllerTest {
    
    private static final String INVALID_SAVE_GROUP_ANSWER_RESULT = 'Invalid group answer saving.';

    @TestSetup
    static void setup() {
        Survey__c testSurvey = TestDataFactory.createSurvey();
        insert testSurvey;
    }

    private static Id getTestSurveyId() {
        Survey__c testSurvey = [SELECT Id
                                FROM Survey__c
                                WHERE Name = :TestDataFactory.TEST_VALUE];
        return testSurvey.Id;      
    }
    
    @isTest
    static void testPositiveSaveGroupAnswer() {
        Group_Answer__c testGroupAnswer = new Group_Answer__c(Survey__c = getTestSurveyId());
        Id savedGroupAnswerId = GroupAnswerController.saveGroupAnswer(testGroupAnswer);
        System.assertNotEquals(null, savedGroupAnswerId, INVALID_SAVE_GROUP_ANSWER_RESULT);
    }

    @isTest
    static void testNegativeSaveGroupAnswer() {
        AuraHandledException auraExc = null;
        try {
            Group_Answer__c testGroupAnswer = new Group_Answer__c();
            Id savedGroupAnswerId = GroupAnswerController.saveGroupAnswer(testGroupAnswer);
        } catch(AuraHandledException exc) {
            auraExc = exc;
        }
        System.assertNotEquals(null, auraExc, INVALID_SAVE_GROUP_ANSWER_RESULT);
    }
    
}