force-app/main/default/objects/Survey_Setting__c/Survey_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Survey Setting</label>
</CustomObject>

force-app/main/default/objects/Survey_Setting__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SurveySettingController.cls
public with sharing class SurveySettingController {
  private static final String AMOUNT_SETTING_NAME = 'Max Question Amount';
  private static final String MAX_TRIGGER_RULE_ANOUNT_SETTING_NAME = 'Max Trigger Rule Amount';

  @AuraEnabled(cacheable=true)
  public static Integer getMaxQuestionAmount() {
    Survey_Setting__c setting = Survey_Setting__c.getValues(AMOUNT_SETTING_NAME);
    return Integer.valueOf(setting.Value__c);
  }

  @AuraEnabled(cacheable=true)
  public static Integer getMaxTriggerRuleAmount() {
    Survey_Setting__c setting = Survey_Setting__c.getValues(MAX_TRIGGER_RULE_ANOUNT_SETTING_NAME);
    return Integer.valueOf(setting.Value__c);
  }
}