force-app/main/default/objects/Survey_Setting__c/Survey_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Survey Setting</label>
</CustomObject>

force-app/main/default/objects/Survey_Setting__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <description>Background color for survey.</description>
    <label>Background Color</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__c/fields/Max_Question_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Question_Amount__c</fullName>
    <description>Max amount of questions available for creating in survey construcor.</description>
    <label>Max Question Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__c/fields/Max_Trigger_Rule_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Trigger_Rule_Amount__c</fullName>
    <description>Max amount of trigger rules available for creation and visible on Setup Trigger Rules Screen.</description>
    <label>Max Trigger Rule Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__c/fields/Min_Question_Amount__c.field-meta.xml
<CustomField>
    <fullName>Min_Question_Amount__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Min amount of questions available for creating in survey constructor.</description>
    <label>Min Question Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__c/fields/Page_Question_Amount__c.field-meta.xml
<CustomField>
    <fullName>Page_Question_Amount__c</fullName>
    <description>Amount of questions displayed on Add Questions ForSurvey screen of survey constructor.</description>
    <label>Page Question Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SurveyEmailConfig__c/SurveyEmailConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Набор настроек для создания и отправки электронного письма.</description>
    <label>SurveyEmailConfig</label>
</CustomObject>

force-app/main/default/objects/SurveyEmailConfig__c/fields/Company_Config__c.field-meta.xml
<CustomField>
    <fullName>Company_Config__c</fullName>
    <label>Company Config</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyEmailConfig__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyEmailConfig__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyEmailConfig__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyEmailConfig__c/fields/Url_Config__c.field-meta.xml
<CustomField>
    <fullName>Url_Config__c</fullName>
    <label>Url Config</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PostInstallConfig.cls
global with sharing class PostInstallConfig implements InstallHandler {

    @testVisible private static final String CUSTOM_SETTING_RECORD_NAME = 'Main';
    
    @testVisible private static final Decimal DEFAULT_MAX_QUESTIONS_AMOUNT = 15;
    @testVisible private static final Decimal DEFAULT_MIN_QUESTIONS_AMOUNT = 1;
    @testVisible private static final Decimal DEFAULT_MAX_TRIGGER_RULE_AMOUNT = 5;
    @testVisible private static final Decimal DEFAULT_PAGE_QUESTION_AMOUNT = 5;
    @testVisible private static final String DEFAULT_BACKGROUND_COLOR = '#5E8AC0';

    @testVisible private static final String DEFAULT_COMPANY_CONFIG = 'COMPANY';
    @testVisible private static final String DEFAULT_DISPLAY_NAME = 'Survey';
    @testVisible private static final String DEFAULT_SUBJECT = 'Survey';
    @testVisible private static final String DEFAULT_TEMPLATE_NAME = 'Main Template';
    @testVisible private static final String DEFAULT_URL_CONFIG = 'URL';

    global void onInstall(InstallContext context) {
        if(context.previousVersion() == null) {
            createSurveyCustomSettingRecord();
            createEmailCustomSettingRecord();
        } else {
            if(!isSurveySettingRecordExisting()) {
                createSurveyCustomSettingRecord();
            }
            if(!isEmailSettingRecordExisting()) {
                createEmailCustomSettingRecord();
            }
        }
    }

    @testVisible private static void createSurveyCustomSettingRecord() {
        Survey_Setting__c surveySetting = new Survey_Setting__c(
            Name = CUSTOM_SETTING_RECORD_NAME,
            Max_Question_Amount__c = DEFAULT_MAX_QUESTIONS_AMOUNT,
            Min_Question_Amount__c = DEFAULT_MIN_QUESTIONS_AMOUNT,
            Max_Trigger_Rule_Amount__c = DEFAULT_MAX_TRIGGER_RULE_AMOUNT,
            Page_Question_Amount__c = DEFAULT_PAGE_QUESTION_AMOUNT,
            Background_Color__c = DEFAULT_BACKGROUND_COLOR
        );

        insert surveySetting;
    }

    @testVisible private static void createEmailCustomSettingRecord() {
        SurveyEmailConfig__c surveySetting = new SurveyEmailConfig__c(
            Name = CUSTOM_SETTING_RECORD_NAME,
            Company_Config__c = DEFAULT_COMPANY_CONFIG,
            Display_Name__c = DEFAULT_DISPLAY_NAME,
            Subject__c = DEFAULT_SUBJECT,
            Template_Name__c = DEFAULT_TEMPLATE_NAME,
            Url_Config__c = DEFAULT_URL_CONFIG
        );

        insert surveySetting;
    }

    private Boolean isSurveySettingRecordExisting() {
        List<Survey_Setting__c> settings = [SELECT Id
                                            FROM Survey_Setting__c
                                            LIMIT 1];
        if(settings.size() == 0) {
            return false;
        }
        return true;
    }

    private Boolean isEmailSettingRecordExisting() {
        List<SurveyEmailConfig__c> settings = [SELECT Id
                                               FROM SurveyEmailConfig__c
                                               LIMIT 1];
        if(settings.size() == 0) {
            return false;
        }
        return true;
    }    
}