force-app/main/default/objects/Survey_Setting__c/Survey_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Survey Setting</label>
</CustomObject>

force-app/main/default/objects/Survey_Setting__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SurveySettingControllerTest.cls
@IsTest
public with sharing class SurveySettingControllerTest {
  private static final String AMOUNT_SETTING_NAME = 'Max Question Amount';
  private static final String TEST_AMOUNT = '5';

  private static final String INVALID_SETTING_VALUE = 'Actual value of setting doesn\'t equal to expected';

  @IsTest
  public static void getMaxQuestionAmountTest() {
    Survey_Setting__c setting = new Survey_Setting__c();
    setting.Name = AMOUNT_SETTING_NAME;
    setting.Value__c = TEST_AMOUNT;
    insert setting;

    Integer savedAmount = SurveySettingController.getMaxQuestionAmount();
    System.assertEquals(Integer.valueOf(TEST_AMOUNT), savedAmount, INVALID_SETTING_VALUE);
  }
}